name: build-on-main

on:
  push:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go get .

    - name: Build
      run: GOOS=linux GOARCH=${{ matrix.arch }} go build -v ./...

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: mysqlscepserver-linux-${{ matrix.arch }}
        path: |
          mysqlscepserver
          schema.sql
